# Generated by Django 4.2.16 on 2026-05-01 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_remove_audit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perm_categories', models.BooleanField(default=True, verbose_name='Catégories')),
                ('perm_matieres', models.BooleanField(default=True, verbose_name='Matières')),
                ('perm_comptes', models.BooleanField(default=True, verbose_name="Comptes d'imputation")),
                ('perm_achats', models.BooleanField(default=True, verbose_name='Achats')),
                ('perm_dons', models.BooleanField(default=True, verbose_name='Dons')),
                ('perm_legs', models.BooleanField(default=True, verbose_name='Legs')),
                ('perm_dotations', models.BooleanField(default=True, verbose_name='Dotations')),
                ('perm_prets', models.BooleanField(default=True, verbose_name='Prêts accordés')),
                ('perm_retours_fournisseurs', models.BooleanField(default=True, verbose_name='Retours fournisseurs')),
                ('perm_stock_courant', models.BooleanField(default=True, verbose_name='Stock courant (par dépôt)')),
                ('perm_stock_actuel', models.BooleanField(default=True, verbose_name='Stock actuel (tous dépôts)')),
                ('perm_mouvements', models.BooleanField(default=True, verbose_name='Mouvements de stock')),
                ('perm_sorties_stock', models.BooleanField(default=True, verbose_name='Sorties de stock')),
                ('perm_transferts', models.BooleanField(default=False, verbose_name='Transferts inter-dépôts')),
                ('perm_sorties_definitives', models.BooleanField(default=True, verbose_name='Sorties définitives')),
                ('perm_reforme', models.BooleanField(default=False, verbose_name='Réforme')),
                ('perm_fournisseurs', models.BooleanField(default=True, verbose_name='Fournisseurs')),
                ('perm_donateurs', models.BooleanField(default=True, verbose_name='Donateurs')),
                ('perm_depots', models.BooleanField(default=True, verbose_name='Dépôts / Sites')),
                ('perm_services', models.BooleanField(default=True, verbose_name='Services')),
                ('perm_unites', models.BooleanField(default=True, verbose_name='Unités de mesure')),
                ('perm_livre_journal', models.BooleanField(default=True, verbose_name='Grand Journal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Permissions agent',
                'verbose_name_plural': 'Permissions agents',
                'indexes': [models.Index(fields=['user'], name='core_agentp_user_id_820229_idx')],
            },
        ),
    ]
