# Generated by Django 4.2.16 on 2026-05-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_agent_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentpermission',
            name='perm_comptes_gestion',
            field=models.BooleanField(default=False, verbose_name='Comptes de gestion'),
        ),
        migrations.AddField(
            model_name='agentpermission',
            name='perm_fiches_stock',
            field=models.BooleanField(default=True, verbose_name='Fiches de stock'),
        ),
        migrations.AddField(
            model_name='agentpermission',
            name='perm_grand_livre',
            field=models.BooleanField(default=True, verbose_name='Grand Livre (par matière)'),
        ),
        migrations.AddField(
            model_name='agentpermission',
            name='perm_pv_recensement',
            field=models.BooleanField(default=False, verbose_name='PV de recensement'),
        ),
        migrations.AddField(
            model_name='agentpermission',
            name='perm_reformes_docs',
            field=models.BooleanField(default=False, verbose_name='Réformes & Destructions (docs)'),
        ),
    ]
