# Generated by Django 4.2.16 on 2026-05-01 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_repr', models.CharField(blank=True, help_text="Valeur figée au moment de l'action ; reste lisible même si le compte est supprimé ultérieurement.", max_length=150, verbose_name='Nom (snapshot)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Clé de session')),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('VALIDATION', 'Validation'), ('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion'), ('ECHEC_CNX', 'Échec de connexion'), ('EXPORT', 'Export'), ('IMPRESSION', 'Impression document')], db_index=True, max_length=20, verbose_name='Action')),
                ('app_label', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Application')),
                ('model_name', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Modèle')),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='ID objet')),
                ('object_repr', models.CharField(blank=True, help_text="str(instance) au moment de l'action.", max_length=300, verbose_name='Représentation')),
                ('changes', models.JSONField(blank=True, help_text='{ "champ": { "avant": valeur, "apres": valeur } }', null=True, verbose_name='Changements')),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Horodatage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Entrée d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['app_label', 'model_name'], name='audit_app_model_idx'), models.Index(fields=['user', 'timestamp'], name='audit_user_time_idx'), models.Index(fields=['action', 'timestamp'], name='audit_action_time_idx'), models.Index(fields=['object_id', 'model_name'], name='audit_obj_model_idx')],
            },
        ),
    ]
